<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Catalog;
use App\Models\Genre;
use App\Models\Person;
use App\Models\Award;
use App\Models\Rating;

class CatalogSeeder extends Seeder
{
    public function run()
    {
        // Pega todos os dados das tabelas relacionadas para evitar múltiplas queries
        $genres = Genre::all();
        $people = Person::all();
        $awards = Award::all();

        // --- SEEDER DE FILMES (20 exemplos) ---
        $movies = [
            [
                'title' => 'Parasita',
                'original_title' => 'Gisaengchung',
                'year' => 2019,
                'duration' => '2h 12min',
                'synopsis' => 'Desempregados, a família de Ki-taek (Song Kang-ho) nutre um interesse peculiar pela família Park até que eles se veem presos em um inesperado incidente.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=m4jfE-TxC24',
                'director' => 'Bong Joon-ho',
                'cast' => ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
                'genres' => ['Drama', 'Thriller', 'Comédia'],
                'awards' => ['Oscar de Melhor Filme', 'Oscar de Melhor Diretor', 'Palma de Ouro'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.5']],
                'is_popular' => true,
            ],
            [
                'title' => 'Coringa',
                'original_title' => 'Joker',
                'year' => 2019,
                'duration' => '2h 2min',
                'synopsis' => 'Um comediante fracassado mergulha na loucura e se torna um ícone psicopático do crime em Gotham City.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=jfVTJm9NilA',
                'director' => 'Todd Phillips',
                'cast' => ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz'],
                'genres' => ['Drama', 'Crime', 'Thriller'],
                'awards' => ['Oscar de Melhor Ator', 'Leão de Ouro'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.4']],
                'is_popular' => true,
            ],
            [
                'title' => 'Era Uma Vez em... Hollywood',
                'original_title' => 'Once Upon a Time in Hollywood',
                'year' => 2019,
                'duration' => '2h 41min',
                'synopsis' => 'Um ator de televisão apagado e seu dublê se esforçam para alcançar a fama e o sucesso na indústria cinematográfica durante os anos finais da Era de Ouro de Hollywood.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=Bbk_ZSh5BWQ',
                'director' => 'Quentin Tarantino',
                'cast' => ['Leonardo DiCaprio', 'Brad Pitt', 'Margot Robbie'],
                'genres' => ['Drama', 'Comédia'],
                'awards' => ['Oscar de Melhor Ator Coadjuvante'],
                'ratings' => [['source' => 'IMDb', 'score' => '7.6']],
                'is_popular' => true,
            ],
            [
                'title' => 'Duna',
                'original_title' => 'Dune: Part One',
                'year' => 2021,
                'duration' => '2h 35min',
                'synopsis' => 'Paul Atreides é um jovem prodígio com um futuro grandioso e envolto em mistério que precisa viajar para o planeta mais perigoso do universo para garantir o futuro de sua família e seu povo.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=hfLkFZWFmLM',
                'director' => 'Denis Villeneuve',
                'cast' => ['Timothée Chalamet', 'Rebecca Ferguson', 'Oscar Isaac'],
                'genres' => ['Ficção Científica', 'Aventura', 'Drama'],
                'awards' => ['Oscar de Melhor Cinematografia', 'Oscar de Melhor Som'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.0']],
                'is_popular' => true,
            ],
            [
                'title' => 'Não Olhe Para Cima',
                'original_title' => "Don't Look Up",
                'year' => 2021,
                'duration' => '2h 18min',
                'synopsis' => 'Dois astrônomos em pânico fazem uma digressão mediática para avisar a humanidade sobre um cometa mortal em rota de colisão com a Terra.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/th4E1yqsE8DGpAseLiUrI60Hf8V.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=c1nToClX_3w',
                'director' => 'Adam McKay',
                'cast' => ['Leonardo DiCaprio', 'Jennifer Lawrence', 'Meryl Streep'],
                'genres' => ['Comédia', 'Drama', 'Ficção Científica'],
                'awards' => ['Indicado ao Oscar de Melhor Filme'],
                'ratings' => [['source' => 'IMDb', 'score' => '7.2']],
                'is_popular' => true,
            ],
            [
                'title' => 'Ataque dos Cães',
                'original_title' => 'The Power of the Dog',
                'year' => 2021,
                'duration' => '2h 6min',
                'synopsis' => 'Um fazendeiro durão trava uma guerra de ameaças contra a nova esposa do irmão e seu filho adolescente, até que antigos segredos vêm à tona.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/epb8WAquLI1S38HWLaHwSdKvxHm.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=ZwXNDdiSAsE',
                'director' => 'Jane Campion',
                'cast' => ['Benedict Cumberbatch', 'Kirsten Dunst', 'Jesse Plemons'],
                'genres' => ['Drama', 'Velho Oeste'],
                'awards' => ['Oscar de Melhor Direção'],
                'ratings' => [['source' => 'IMDb', 'score' => '6.8']],
                'is_popular' => false,
            ],
            [
                'title' => 'Tudo em Todo Lugar ao Mesmo Tempo',
                'original_title' => 'Everything Everywhere All at Once',
                'year' => 2022,
                'duration' => '2h 19min',
                'synopsis' => 'Uma imigrante chinesa de meia idade se envolve em uma aventura louca, onde só ela pode salvar o mundo explorando outros universos que se conectam com as vidas que ela poderia ter levado.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=kULcXm9V7aY',
                'director' => 'Daniel Kwan',
                'cast' => ['Michelle Yeoh', 'Stephanie Hsu', 'Ke Huy Quan'],
                'genres' => ['Ação', 'Aventura', 'Comédia'],
                'awards' => ['Oscar de Melhor Filme', 'Oscar de Melhor Atriz'],
                'ratings' => [['source' => 'IMDb', 'score' => '7.8']],
                'is_popular' => true,
            ],
            [
                'title' => 'Top Gun: Maverick',
                'original_title' => 'Top Gun: Maverick',
                'year' => 2022,
                'duration' => '2h 10min',
                'synopsis' => 'Após mais de trinta anos de serviço como um dos melhores aviadores da Marinha, Pete Mitchell está onde pertence, ultrapassando os limites como um piloto de teste intrépido e evitando a promoção de posto que o manteria em terra.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=9Jgua93Xhcw',
                'director' => 'Joseph Kosinski',
                'cast' => ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly'],
                'genres' => ['Ação', 'Drama'],
                'awards' => ['Indicado ao Oscar de Melhor Filme'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.2']],
                'is_popular' => true,
            ],
            [
                'title' => 'Os Fabelmans',
                'original_title' => 'The Fabelmans',
                'year' => 2022,
                'duration' => '2h 31min',
                'synopsis' => 'Crescendo no Arizona da era pós-Segunda Guerra Mundial, um jovem chamado Sammy Fabelman descobre um segredo de família e explora como o poder dos filmes pode ajudá-lo a ver a verdade.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/h7llKkqkkJtJrTOaDLuVeUYDQ7I.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=R4eRHRPs8Ss',
                'director' => 'Steven Spielberg',
                'cast' => ['Gabriel LaBelle', 'Michelle Williams', 'Paul Dano'],
                'genres' => ['Drama', 'Comédia'],
                'awards' => ['Indicado ao Oscar de Melhor Filme'],
                'ratings' => [['source' => 'IMDb', 'score' => '7.5']],
                'is_popular' => false,
            ],
            [
                'title' => 'Avatar: O Caminho da Água',
                'original_title' => 'Avatar: The Way of Water',
                'year' => 2022,
                'duration' => '3h 12min',
                'synopsis' => "Jake Sully vive com sua nova família na lua extrassolar Pandora. Uma vez que uma ameaça familiar retorna para terminar o que foi iniciado anteriormente, Jake deve trabalhar com Neytiri e o exército da raça Na'vi para proteger sua casa.",
                'poster_url' => 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=x5pZI-DmtrE',
                'director' => 'James Cameron',
                'cast' => ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver'],
                'genres' => ['Ação', 'Aventura', 'Fantasia'],
                'awards' => ['Indicado ao Oscar de Melhores Efeitos Visuais'],
                'ratings' => [['source' => 'IMDb', 'score' => '7.6']],
                'is_popular' => true,
            ],
            [
                'title' => 'Não! Não Olhe!',
                'original_title' => 'Nope',
                'year' => 2022,
                'duration' => '2h 10min',
                'synopsis' => 'Os moradores de uma ravina solitária no deserto da Califórnia testemunham um fenómeno misterioso e assustador.',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=l05c7Z8aD0Q',
                'director' => 'Jordan Peele',
                'cast' => ['Daniel Kaluuya', 'Keke Palmer', 'Steven Yeun'],
                'genres' => ['Terror', 'Mistério', 'Ficção Científica'],
                'awards' => ['Indicado ao Oscar de Melhores Efeitos Visuais'],
                'ratings' => [['source' => 'IMDb', 'score' => '6.8']],
                'is_popular' => true,
            ],
            [
                'title' => 'Babilônia',
                'original_title' => 'Babylon',
                'year' => 2022,
                'duration' => '3h 9min',
                'synopsis' => 'Um conto de ambições exageradas e excessos escandalosos, ele traça a ascensão e queda de múltiplos personagens durante uma era de desenfreada decadência e depravação no início de Hollywood.',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/wjOHjWCUE0YzDiEzKv8AfqHj3ir.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=binSx3SfsaM',
                'director' => 'Damien Chazelle',
                'cast' => ['Margot Robbie', 'Brad Pitt', 'Diego Calva'],
                'genres' => ['Drama', 'Comédia'],
                'awards' => ['Oscar de Melhor Trilha Sonora'],
                'ratings' => [['source' => 'IMDb', 'score' => '7.1']],
                'is_popular' => false,
            ],
            [
                'title' => 'Oppenheimer',
                'original_title' => 'Oppenheimer',
                'year' => 2023,
                'duration' => '3h 0min',
                'synopsis' => 'A história do cientista americano J. Robert Oppenheimer e seu papel no desenvolvimento da bomba atômica.',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=F3OxA9Cz17A',
                'director' => 'Christopher Nolan',
                'cast' => ['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.'],
                'genres' => ['Drama', 'História', 'Biografia'],
                'awards' => ['Oscar de Melhor Filme', 'Oscar de Melhor Ator'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.3']],
                'is_popular' => true,
            ],
            [
                'title' => 'Barbie',
                'original_title' => 'Barbie',
                'year' => 2023,
                'duration' => '1h 54min',
                'synopsis' => 'Viver na Terra da Barbie é ser um ser perfeito em um lugar perfeito. A menos que você tenha uma crise existencial completa. Ou que você seja um Ken.',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=Ujs1Ud7k49M',
                'director' => 'Greta Gerwig',
                'cast' => ['Margot Robbie', 'Ryan Gosling', 'America Ferrera'],
                'genres' => ['Comédia', 'Aventura', 'Fantasia'],
                'awards' => ['Indicado ao Oscar de Melhor Filme'],
                'ratings' => [['source' => 'IMDb', 'score' => '6.9']],
                'is_popular' => true,
            ],
            [
                'title' => 'Pânico VI',
                'original_title' => 'Scream VI',
                'year' => 2023,
                'duration' => '2h 3min',
                'synopsis' => 'Os sobreviventes dos assassinatos de Ghostface deixam Woodsboro para trás e iniciam um novo capítulo na cidade de Nova York.',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=QOgdGhA9gos',
                'director' => 'Matt Bettinelli-Olpin',
                'cast' => ['Melissa Barrera', 'Jenna Ortega', 'Jasmin Savoy Brown'],
                'genres' => ['Terror', 'Mistério', 'Thriller'],
                'awards' => ['Teen Choice Award de Melhor Filme de Terror'],
                'ratings' => [['source' => 'IMDb', 'score' => '6.5']],
                'is_popular' => true,
            ],
            [
                'title' => 'John Wick 4: Baba Yaga',
                'original_title' => 'John Wick: Chapter 4',
                'year' => 2023,
                'duration' => '2h 49min',
                'synopsis' => 'John Wick descobre um modo para derrotar a Alta Cúpula. Mas, antes que possa conquistar a sua liberdade, Wick deve enfrentar um novo inimigo com alianças poderosas no mundo todo e forças que transformam velhos amigos em inimigos.',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=gZtmzT9Wgrw',
                'director' => 'Chad Stahelski',
                'cast' => ['Keanu Reeves', 'Donnie Yen', 'Bill Skarsgård'],
                'genres' => ['Ação', 'Thriller', 'Crime'],
                'awards' => ['Saturn Award de Melhor Filme de Ação'],
                'ratings' => [['source' => 'IMDb', 'score' => '7.7']],
                'is_popular' => true,
            ],
            [
                'title' => 'Guardiões da Galáxia Vol. 3',
                'original_title' => 'Guardians of the Galaxy Vol. 3',
                'year' => 2023,
                'duration' => '2h 30min',
                'synopsis' => 'Após a perda de Gamora, Peter Quill ainda está chateado e deve reunir os Guardiões da Galáxia em uma missão para defender o universo e proteger Rocket.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=5UVaA6SGRZA',
                'director' => 'James Gunn',
                'cast' => ['Chris Pratt', 'Zoe Saldana', 'Dave Bautista'],
                'genres' => ['Ação', 'Aventura', 'Comédia'],
                'awards' => ['Teen Choice Award de Melhor Filme de Ficção Científica'],
                'ratings' => [['source' => 'IMDb', 'score' => '7.9']],
                'is_popular' => true,
            ],
            [
                'title' => 'Homem-Aranha: Através do Aranhaverso',
                'original_title' => 'Spider-Man: Across the Spider-Verse',
                'year' => 2023,
                'duration' => '2h 20min',
                'synopsis' => 'Viajando pelo multiverso, Miles Morales conhece um novo time de Pessoas-Aranha, formado por heróis de diversas dimensões. Mas quando os heróis entram em conflito sobre como lidar com uma nova ameaça, Miles se vê em um impasse.',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=LZBlXkDvhh4',
                'director' => 'Joaquim Dos Santos',
                'cast' => ['Shameik Moore', 'Hailee Steinfeld', 'Brian Tyree Henry'],
                'genres' => ['Animação', 'Ação', 'Aventura'],
                'awards' => ['Oscar de Melhor Filme de Animação'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.7']],
                'is_popular' => true,
            ],
            [
                'title' => 'Pobres Criaturas',
                'original_title' => 'Poor Things',
                'year' => 2023,
                'duration' => '2h 21min',
                'synopsis' => 'A incrível história e a fantástica evolução de Bella Baxter, uma jovem trazida de volta à vida por um cientista brilhante e pouco ortodoxo.',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=9DEOJkmZLd8',
                'director' => 'Yorgos Lanthimos',
                'cast' => ['Emma Stone', 'Mark Ruffalo', 'Willem Dafoe'],
                'genres' => ['Comédia', 'Drama', 'Romance'],
                'awards' => ['Oscar de Melhor Atriz', 'Oscar de Melhor Design de Produção'],
                'ratings' => [['source' => 'IMDb', 'score' => '7.8']],
                'is_popular' => false,
            ]
        ];

        // --- SEEDER DE SÉRIES (20 exemplos ) ---
        $series = [
            [
                'title' => 'Chernobyl',
                'original_title' => 'Chernobyl',
                'year' => 2019,
                'duration' => '1 temporada',
                'synopsis' => 'Minissérie em cinco partes que conta a história do pior acidente causado pelo homem na história, o desastre da Usina Nuclear de Chernobyl.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=jQO2EhzG-uU',
                'director' => 'Johan Renck',
                'cast' => ['Jared Harris', 'Stellan Skarsgård', 'Emily Watson'],
                'genres' => ['Drama', 'História'],
                'awards' => ['Emmy de Melhor Minissérie', 'Globo de Ouro de Melhor Minissérie'],
                'ratings' => [['source' => 'IMDb', 'score' => '9.4']],
                'is_popular' => true,
            ],
            [
                'title' => 'Breaking Bad',
                'original_title' => 'Breaking Bad',
                'year' => 2008,
                'duration' => '5 temporadas',
                'synopsis' => 'Um professor de química diagnosticado com câncer de pulmão se transforma em fabricante e vendedor de metanfetamina, a fim de garantir o futuro da sua família.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
                'trailer_url' => 'https://www.imdb.com/pt/video/vi338798873/?playlistId=tt0903747&ref_=ext_shr_lnk',
                'director' => 'Vince Gilligan',
                'cast' => ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'],
                'genres' => ['Drama', 'Crime', 'Suspense'],
                'awards' => ['Emmy de Melhor Drama', 'Emmy de Melhor Ator'],
                'ratings' => [['source' => 'IMDb', 'score' => '9.5']],
                'is_popular' => true,
            ],
            [
                'title' => 'Game of Thrones',
                'original_title' => 'Game of Thrones',
                'year' => 2011,
                'duration' => '8 temporadas',
                'synopsis' => 'Nove famílias nobres lutam pelo controle sobre as terras míticas de Westeros, enquanto um antigo inimigo retorna depois de estar adormecido por milhares de anos.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=KPLWWIOCOOQ',
                'director' => 'David Benioff',
                'cast' => ['Emilia Clarke', 'Peter Dinklage', 'Kit Harington'],
                'genres' => ['Drama', 'Fantasia', 'Aventura'],
                'awards' => ['Emmy de Melhor Drama', 'Emmy de Melhor Ator Coadjuvante'],
                'ratings' => [['source' => 'IMDb', 'score' => '9.3']],
                'is_popular' => true,
            ],
            [
                'title' => 'Stranger Things',
                'original_title' => 'Stranger Things',
                'year' => 2016,
                'duration' => '4 temporadas',
                'synopsis' => 'Depois do desaparecimento de un menino, sua mãe, um chefe de polícia e seus amigos precisam enfrentar forças aterrorizantes para trazê-lo de volta.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=U4sndXXtrtE',
                'director' => 'Matt Duffer',
                'cast' => ['Millie Bobby Brown', 'Finn Wolfhard', 'David Harbour'],
                'genres' => ['Drama', 'Ficção Científica', 'Terror'],
                'awards' => ['SAG Award de Melhor Elenco', 'Critics Choice Award'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.7']],
                'is_popular' => true,
            ],
            [
                'title' => 'The Crown',
                'original_title' => 'The Crown',
                'year' => 2016,
                'duration' => '6 temporadas',
                'synopsis' => 'Segue as rivalidades políticas e romance do reinado da rainha Elizabeth II e os eventos que moldaram a segunda metade do século 20.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/1DDE0Z2Y805rqfkEjPbZsMLyPwa.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=dFZC-_T_irA',
                'director' => 'Peter Morgan',
                'cast' => ['Claire Foy', 'Olivia Colman', 'Imelda Staunton'],
                'genres' => ['Drama', 'História', 'Biografia'],
                'awards' => ['Globo de Ouro de Melhor Série', 'Emmy de Melhor Atriz'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.6']],
                'is_popular' => true,
            ],
            [
                'title' => 'The Mandalorian',
                'original_title' => 'The Mandalorian',
                'year' => 2019,
                'duration' => '3 temporadas',
                'synopsis' => 'Após a queda do Império, um mandaloriano solitário trilha seu caminho pela galáxia com seu enjeitado, Grogu.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=5gWQXeJTjCg',
                'director' => 'Jon Favreau',
                'cast' => ['Pedro Pascal', 'Gina Carano', 'Carl Weathers'],
                'genres' => ['Ficção Científica', 'Aventura', 'Ação'],
                'awards' => ['Emmy de Melhores Efeitos Visuais'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.7']],
                'is_popular' => true,
            ],
            [
                'title' => 'Ozark',
                'original_title' => 'Ozark',
                'year' => 2017,
                'duration' => '4 temporadas',
                'synopsis' => 'Um consultor financeiro arrasta sua família de Chicago para o Missouri, onde ele deve lavar uma grande quantidade em cinco anos para apaziguar um chefe do tráfico.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/m73bD8VjibSKuTWg597GQVyVhSb.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=WgiCNsBYA00',
                'director' => 'Bill Dubuque',
                'cast' => ['Jason Bateman', 'Laura Linney', 'Sofia Hublitz'],
                'genres' => ['Drama', 'Crime', 'Suspense'],
                'awards' => ['Emmy de Melhor Ator', 'SAG Award de Melhor Atriz'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.4']],
                'is_popular' => true,
            ],
            [
                'title' => 'The Witcher',
                'original_title' => 'The Witcher',
                'year' => 2019,
                'duration' => '3 temporadas',
                'synopsis' => 'Geralt de Rivia, um caçador de monstros, luta contra um mundo onde as vezes as pessoas são mais temidas do que as bestas.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=TN-_xS4Kdpg',
                'director' => 'Lauren Schmidt',
                'cast' => ['Henry Cavill', 'Anya Chalotra', 'Freya Allan'],
                'genres' => ['Fantasia', 'Drama', 'Aventura'],
                'awards' => ['Saturn Award de Melhor Série de Fantasia'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.2']],
                'is_popular' => true,
            ],
            [
                'title' => 'A Casa do Dragão',
                'original_title' => 'House of the Dragon',
                'year' => 2022,
                'duration' => '2 temporadas',
                'synopsis' => "A história da House Targaryen se passa 200 anos antes dos eventos de 'Game of Thrones'.",
                'poster_url' => 'https://image.tmdb.org/t/p/original/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=97YXokOdZgU',
                'director' => 'Ryan Condal',
                'cast' => ['Paddy Considine', "Emma D'Arcy", 'Matt Smith'],
                'genres' => ['Drama', 'Fantasia', 'Aventura'],
                'awards' => ['Critics Choice Award de Melhor Série de Drama'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.5']],
                'is_popular' => true,
            ],
            [
                'title' => 'The Last of Us',
                'original_title' => 'The Last of Us',
                'year' => 2023,
                'duration' => '2 temporadas',
                'synopsis' => 'Joel e Ellie, um par conectado pela dureza do mundo em que vivem, são forçados a suportar circunstâncias brutais e assassinos implacáveis ​​em uma jornada pela América pós-pandemia.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=0vB2lHQim3Q',
                'director' => 'Neil Druckmann',
                'cast' => ['Pedro Pascal', 'Bella Ramsey', 'Anna Torv'],
                'genres' => ['Drama', 'Terror', 'Ficção Científica'],
                'awards' => ['Critics Choice Award de Melhor Série', 'Writers Guild Award'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.7']],
                'is_popular' => true,
            ],
            [
                'title' => 'Wandinha',
                'original_title' => 'Wednesday',
                'year' => 2022,
                'duration' => '1 temporada',
                'synopsis' => 'Inteligente, sarcástica e apática, Wandinha Addams pode estar meio morta por dentro, mas na Escola Nunca Mais ela faz amigos, inimigos e investiga assassinatos.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/9PFonBhy4cQy7Jz20NpMygczOkv.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=855QySYhW1s',
                'director' => 'Alfred Gough',
                'cast' => ['Jenna Ortega', 'Emma Myers', 'Enid Sinclair'],
                'genres' => ['Comédia', 'Terror', 'Mistério'],
                'awards' => ['Golden Globe de Melhor Atriz', 'SAG Award de Melhor Atriz'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.1']],
                'is_popular' => true,
            ],
            [
                'title' => 'Succession',
                'original_title' => 'Succession',
                'year' => 2018,
                'duration' => '4 temporadas',
                'synopsis' => 'A saga de uma família disfuncional de magnatas da mídia que luta pelo controle de seu império empresarial.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/7HW47XbkNQ5fiwQFYGWdw9gs144.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=t3D3ewle7XY',
                'director' => 'Jesse Armstrong',
                'cast' => ['Jeremy Strong', 'Brian Cox', 'Sarah Snook'],
                'genres' => ['Drama', 'Comédia'],
                'awards' => ['Emmy de Melhor Drama', 'Golden Globe de Melhor Série'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.8']],
                'is_popular' => true,
            ],
            [
                'title' => 'Euphoria',
                'original_title' => 'Euphoria',
                'year' => 2019,
                'duration' => '2 temporadas',
                'synopsis' => 'Segue um grupo de estudantes do ensino médio enquanto navegam pelo amor e amizades em um mundo de drogas, sexo, trauma e mídia social.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/jtnfNzqZwN4E32FGGxx1YZaBWWf.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=dt-cA0u6Png',
                'director' => 'Sam Levinson',
                'cast' => ['Zendaya', 'Hunter Schafer', 'Jacob Elordi'],
                'genres' => ['Drama', 'Romance'],
                'awards' => ['Emmy de Melhor Atriz', 'Critics Choice Award'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.4']],
                'is_popular' => true,
            ],
            [
                'title' => 'Peaky Blinders: Sangue, Apostas e Navalhas',
                'original_title' => 'Peaky Blinders',
                'year' => 2013,
                'duration' => '6 temporadas',
                'synopsis' => 'Depois de servir no Exército, Thomas Shelby e seus irmãos voltam para controlar a cidade, mas, conforme as ambições de Shelby se estendem, ele planeja construir seu próprio negócio e impedir qualquer um que atrapalhe.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=svmIUWMVo2Y',
                'director' => 'Steven Knight',
                'cast' => ['Cillian Murphy', 'Paul Anderson', 'Helen McCrory'],
                'genres' => ['Drama', 'Crime', 'História'],
                'awards' => ['BAFTA de Melhor Drama', 'National Television Award'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.8']],
                'is_popular' => true,
            ],
            [
                'title' => 'The Boys',
                'original_title' => 'The Boys',
                'year' => 2019,
                'duration' => '4 temporadas',
                'synopsis' => 'Um grupo de vigilantes luta contra super-heróis corruptos que abusam de seus superpoderes.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/stTEycfG9928HYGEISBFaG1ngjM.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=m1lv458bxdg',
                'director' => 'Eric Kripke',
                'cast' => ['Karl Urban', 'Jack Quaid', 'Antony Starr'],
                'genres' => ['Ação', 'Comédia', 'Ficção Científica'],
                'awards' => ['Critics Choice Award', 'Saturn Award de Melhor Série'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.7']],
                'is_popular' => true,
            ],
            [
                'title' => 'Bridgerton',
                'original_title' => 'Bridgerton',
                'year' => 2020,
                'duration' => '3 temporadas',
                'synopsis' => 'Riqueza, luxúria e traição no cenário da era da Regência na Inglaterra, vista através dos olhos da poderosa família Bridgerton.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/luoKpgVwi1E5nQsi7W0UuKHu2Rq.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=sA6xIbcaZsw',
                'director' => 'Chris Van Dusen',
                'cast' => ['Nicola Coughlan', 'Jonathan Bailey', 'Simone Ashley'],
                'genres' => ['Drama', 'Romance', 'História'],
                'awards' => ['SAG Award de Melhor Elenco', 'NAACP Image Award'],
                'ratings' => [['source' => 'IMDb', 'score' => '7.3']],
                'is_popular' => true,
            ],
            [
                'title' => 'A Casa de Papel',
                'original_title' => 'La Casa de Papel',
                'year' => 2017,
                'duration' => '5 temporadas',
                'synopsis' => 'Um grupo de ladrões peculiares assaltam a Fábrica de Moneda e Timbre para realizar o assalto mais perfeito da história da Espanha e levar para casa bilhões de euros.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/MoEKaPFHABtA1xKoOteirGaHl1.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=Bjo0sVS4-Es',
                'director' => 'Álex Pina',
                'cast' => ['Álvaro Morte', 'Úrsula Corberó', 'Itziar Ituño'],
                'genres' => ['Crime', 'Drama', 'Suspense'],
                'awards' => ['Emmy Internacional', 'Premios Iris'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.2']],
                'is_popular' => true,
            ],
            [
                'title' => 'Round 6',
                'original_title' => 'Ojing-eo geim',
                'year' => 2021,
                'duration' => '2 temporadas',
                'synopsis' => 'Centenas de apostadores com dinheiro em caixa aceitam um convite bizarro para competir em jogos infantis. Por dentro, um prêmio tentador espera com um jogo de sobrevivência de alto risco que tem um prêmio de 40 milhões de dólares em jogo.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=NCJoNNOa7q8',
                'director' => 'Hwang Dong-hyuk',
                'cast' => ['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-joon'],
                'genres' => ['Drama', 'Suspense', 'Ação'],
                'awards' => ['Emmy de Melhor Ator', 'SAG Award de Melhor Ator'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.0']],
                'is_popular' => true,
            ],
            [
                'title' => 'Dark',
                'original_title' => 'Dark',
                'year' => 2017,
                'duration' => '3 temporadas',
                'synopsis' => 'Saga familiar sobrenatural ambientada em uma cidade alemã, onde o desaparecimento de duas crianças expõe as relações entre quatro famílias.',
                'poster_url' => 'https://image.tmdb.org/t/p/original/3Zx8l6JExvtnXN7cDrZyvHhpGCD.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=9RNHKKYJvg8',
                'director' => 'Baran bo Odar',
                'cast' => ['Louis Hofmann', 'Lisa Vicari', 'Maja Schöne'],
                'genres' => ['Drama', 'Ficção Científica', 'Mistério'],
                'awards' => ['Grimme Award', 'German Television Award'],
                'ratings' => [['source' => 'IMDb', 'score' => '8.7']],
                'is_popular' => false,
            ]
        ];

        // Processa os filmes
        foreach ($movies as $movieData ) {
            $this->createCatalog($movieData, 'movie', $genres, $people, $awards);
        }

        // Processa as séries
        foreach ($series as $serieData) {
            $this->createCatalog($serieData, 'series', $genres, $people, $awards);
        }
    }

    /**
     * Função auxiliar para criar um item e seus relacionamentos
     */
    private function createCatalog(array $data, string $type, $genres, $people, $awards)
    {
        // Encontra o ID do diretor
        $directorId = $data['director'] ? $people->where('name', $data['director'])->first()->id : null;

        // Cria o item no banco
        $catalog = Catalog::create([
            'type' => $type,
            'title' => $data['title'],
            'original_title' => $data['original_title'],
            'year' => $data['year'],
            'duration' => $data['duration'],
            'synopsis' => $data['synopsis'],
            'poster_url' => $data['poster_url'],
            'trailer_url' => $data['trailer_url'],
            'director_id' => $directorId,
            'is_popular' => $data['is_popular'] ?? false,
        ]);

        // Associa os gêneros
        $genreIds = $genres->whereIn('name', $data['genres'])->pluck('id');
        $catalog->genres()->attach($genreIds);

        // Associa o elenco
        $castIds = $people->whereIn('name', $data['cast'])->pluck('id');
        $catalog->cast()->attach($castIds);

        // Associa os prêmios
        $awardIds = $awards->whereIn('name', $data['awards'])->pluck('id');
        $catalog->awards()->attach($awardIds);

        // Cria as avaliações
        foreach ($data['ratings'] as $ratingData) {
            Rating::create([
                'catalog_id' => $catalog->id,
                'source' => $ratingData['source'],
                'score' => $ratingData['score'],
            ]);
        }
    }
}
