<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Person; // Certifique-se de que o Model Person existe

class PersonSeeder extends Seeder
{
    public function run()
    {
        $people = [
            ['name' => 'Johan Renck'],
            ['name' => 'Jared Harris'],
            ['name' => 'Stellan Skarsgård'],
            ['name' => 'Emily Watson'],
            ['name' => 'Vince Gilligan'],
            ['name' => 'David Benioff'],
            ['name' => 'Bryan Cranston'],
            ['name' => 'Aaron Paul'],
            ['name' => 'Anna Gunn'],
            ['name' => 'Emilia Clarke'],
            ['name' => 'Peter Dinklage'],
            ['name' => 'Kit Harington'],
            ['name' => 'Matt Duffer'],
            ['name' => 'Ross Duffer'],
            ['name' => 'Millie Bobby Brown'],
            ['name' => 'Finn Wolfhard'],
            ['name' => 'David Harbour'],
            ['name' => 'Peter Morgan'],
            ['name' => 'Claire Foy'],
            ['name' => 'Olivia Colman'],
            ['name' => 'Imelda Staunton'],
            ['name' => 'Jon Favreau'],
            ['name' => 'Pedro Pascal'],
            ['name' => 'Gina Carano'],
            ['name' => 'Carl Weathers'],
            ['name' => 'Bill Dubuque'],
            ['name' => 'Mark Williams'],
            ['name' => 'Jason Bateman'],
            ['name' => 'Laura Linney'],
            ['name' => 'Sofia Hublitz'],
            ['name' => 'Lauren Schmidt'],
            ['name' => 'Henry Cavill'],
            ['name' => 'Anya Chalotra'],
            ['name' => 'Freya Allan'],
            ['name' => 'Ryan Condal'],
            ['name' => 'George R.R. Martin'],
            ['name' => 'Paddy Considine'],
            ['name' => "Emma D'Arcy"],
            ['name' => 'Matt Smith'],
            ['name' => 'Craig Mazin'],
            ['name' => 'Neil Druckmann'],
            ['name' => 'Bella Ramsey'],
            ['name' => 'Anna Torv'],
            ['name' => 'Alfred Gough'],
            ['name' => 'Miles Millar'],
            ['name' => 'Jesse Armstrong'],
            ['name' => 'Jeremy Strong'],
            ['name' => 'Brian Cox'],
            ['name' => 'Sarah Snook'],
            ['name' => 'Sam Levinson'],
            ['name' => 'Steven Knight'],
            ['name' => 'Cillian Murphy'],
            ['name' => 'Paul Anderson'],
            ['name' => 'Helen McCrory'],
            ['name' => 'Eric Kripke'],
            ['name' => 'Karl Urban'],
            ['name' => 'Jack Quaid'],
            ['name' => 'Antony Starr'],
            ['name' => 'Chris Van Dusen'],
            ['name' => 'Nicola Coughlan'],
            ['name' => 'Jonathan Bailey'],
            ['name' => 'Simone Ashley'],
            ['name' => 'Álex Pina'],
            ['name' => 'Álvaro Morte'],
            ['name' => 'Úrsula Corberó'],
            ['name' => 'Itziar Ituño'],
            ['name' => 'Hwang Dong-hyuk'],
            ['name' => 'Lee Jung-jae'],
            ['name' => 'Park Hae-soo'],
            ['name' => 'Wi Ha-joon'],
            ['name' => 'Baran bo Odar'],
            ['name' => 'Jantje Friese'],
            ['name' => 'Louis Hofmann'],
            ['name' => 'Lisa Vicari'],
            ['name' => 'Maja Schöne'],
            ['name' => 'Bong Joon-ho'],
            ['name' => 'Todd Phillips'],
            ['name' => 'Quentin Tarantino'],
            ['name' => 'Denis Villeneuve'],
            ['name' => 'Adam McKay'],
            ['name' => 'Jane Campion'],
            ['name' => 'Daniel Kwan'],
            ['name' => 'Joseph Kosinski'],
            ['name' => 'Steven Spielberg'],
            ['name' => 'James Cameron'],
            ['name' => 'Jordan Peele'],
            ['name' => 'Damien Chazelle'],
            ['name' => 'Christopher Nolan'],
            ['name' => 'Greta Gerwig'],
            ['name' => 'Matt Bettinelli-Olpin'],
            ['name' => 'Chad Stahelski'],
            ['name' => 'James Gunn'],
            ['name' => 'Joaquim Dos Santos'],
            ['name' => 'Yorgos Lanthimos'],
            ['name' => 'Song Kang-ho'],
            ['name' => 'Lee Sun-kyun'],
            ['name' => 'Cho Yeo-jeong'],
            ['name' => 'Joaquin Phoenix'],
            ['name' => 'Robert De Niro'],
            ['name' => 'Zazie Beetz'],
            ['name' => 'Leonardo DiCaprio'],
            ['name' => 'Brad Pitt'],
            ['name' => 'Margot Robbie'],
            ['name' => 'Timothée Chalamet'],
            ['name' => 'Rebecca Ferguson'],
            ['name' => 'Oscar Isaac'],
            ['name' => 'Jennifer Lawrence'],
            ['name' => 'Meryl Streep'],
            ['name' => 'Benedict Cumberbatch'],
            ['name' => 'Kirsten Dunst'],
            ['name' => 'Jesse Plemons'],
            ['name' => 'Michelle Yeoh'],
            ['name' => 'Stephanie Hsu'],
            ['name' => 'Ke Huy Quan'],
            ['name' => 'Tom Cruise'],
            ['name' => 'Miles Teller'],
            ['name' => 'Jennifer Connelly'],
            ['name' => 'Gabriel LaBelle'],
            ['name' => 'Michelle Williams'],
            ['name' => 'Paul Dano'],
            ['name' => 'Sam Worthington'],
            ['name' => 'Zoe Saldana'],
            ['name' => 'Sigourney Weaver'],
            ['name' => 'Daniel Kaluuya'],
            ['name' => 'Keke Palmer'],
            ['name' => 'Steven Yeun'],
            ['name' => 'Diego Calva'],
            ['name' => 'Cillian Murphy'],
            ['name' => 'Emily Blunt'],
            ['name' => 'Robert Downey Jr.'],
            ['name' => 'Ryan Gosling'],
            ['name' => 'America Ferrera'],
            ['name' => 'Melissa Barrera'],
            ['name' => 'Jenna Ortega'],
            ['name' => 'Jasmin Savoy Brown'],
            ['name' => 'Keanu Reeves'],
            ['name' => 'Donnie Yen'],
            ['name' => 'Bill Skarsgård'],
            ['name' => 'Chris Pratt'],
            ['name' => 'Dave Bautista'],
            ['name' => 'Shameik Moore'],
            ['name' => 'Hailee Steinfeld'],
            ['name' => 'Brian Tyree Henry'],
            ['name' => 'Emma Stone'],
            ['name' => 'Mark Ruffalo'],
            ['name' => 'Willem Dafoe'],
        ];
        
        foreach ($people as $person) {
            Person::firstOrCreate($person);
        }
    }
}
